import turtle
dhanya = turtle.Pen()
sahana = turtle.Pen()
nilan = turtle.Pen()
aadhi = turtle.Pen()
dhanya.forward(120)
sahana.forward(120)
nilan.forward(150)
aadhi.forward(150)
dhanya.left(90)
dhanya.forward(100)
dhanya.right(90)
dhanya.forward(120)
sahana.right(90)
sahana.forward(100)
sahana.left(90)
sahana.forward(120)
nilan.left(90)
nilan.forward(70)
nilan.right(90)
nilan.forward(60)
aadhi.right(90)
aadhi.forward(70)
aadhi.left(90)
aadhi.forward(60)
